"""empty message

Revision ID: bdb2eb82c364
Revises: c77c9bc02f66
Create Date: 2020-07-04 21:49:27.722295

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bdb2eb82c364'
down_revision = 'c77c9bc02f66'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('city', sa.String(length=120), nullable=True),
    sa.Column('state', sa.String(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('Artist', sa.Column('location_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'Artist', 'Location', ['location_id'], ['id'])
    op.drop_column('Artist', 'city')
    op.drop_column('Artist', 'state')
    op.add_column('Venue', sa.Column('location_id', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'Venue', 'Location', ['location_id'], ['id'])
    op.drop_column('Venue', 'city')
    op.drop_column('Venue', 'state')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('Venue', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Venue', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Venue', type_='foreignkey')
    op.drop_column('Venue', 'location_id')
    op.add_column('Artist', sa.Column('state', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.add_column('Artist', sa.Column('city', sa.VARCHAR(length=120), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'Artist', type_='foreignkey')
    op.drop_column('Artist', 'location_id')
    op.drop_table('Location')
    # ### end Alembic commands ###
